# experiment params
seed: 42
batch_size: 512
n_epochs: 100

data_dir: D:/dataset/vctk/processed
model_dir: D:/models/vcon
train_ratio: 0.9

# resemblyzer.VoiceEncoder encodes wav to 256-dim vector
speaker_emb_dim: 256
# mel-spectrogram bin size
mel_size: 80
# sampling rate
sampling_rate: 22050

# vector-quantization params
emb_dim: 64
n_embed: 256

# optimizer params
optimizer:
  lr: 0.003

# encoder params
encoder:
  n_conv: 3
  channel: 256

# EMA params in vq
ema:
  decay: 0.99
  eps: 0.00005

# decoder params
decoder:
  n_conv: 3
  channel: 256

# postnet params
postnet:
  n_layers: 5
  channel: 256
