# experiment params
exp_name: adain_gan
seed: 42
batch_size: 512
n_epochs: 500

train_ratio: 0.9

# resemblyzer.VoiceEncoder encodes wav to 256-dim vector
speaker_emb_dim: 256
# mel-spectrogram bin size
mel_size: 80
# sampling rate
sampling_rate: 22050

# vector-quantization params
emb_dim: 64
n_embed: 256

# optimizer params
optimizer:
  lr: 0.001
  b1: 0.5
  b2: 0.99

# encoder params
encoder:
  bank_channel: 128
  n_bank: 4
  channel: 128
  kernel_size: 5
  n_layers: 5

# decoder params
decoder:
  channel: 128
  kernel_size: 5
  n_layers: 5

discriminator:
  channels:
    - 64
    - 128
    - 256
    - 512
  n_layers: 5
  kernel_size: 5