# experiment params
exp_name: vqvc
seed: 42
batch_size: 512
n_epochs: 500

train_ratio: 0.98

# resemblyzer.VoiceEncoder encodes wav to 256-dim vector
speaker_emb_dim: 256
# mel-spectrogram bin size
mel_size: 80
# sampling rate
sampling_rate: 22050

# optimizer params
optimizer:
  lr: 0.001

# model params
model:
  in_channel: 80
  channel: 512
