# experiment params
exp_name: autovc
seed: 42
batch_size: 256
n_epochs: 300

train_ratio: 0.95

# resemblyzer.VoiceEncoder encodes wav to 256-dim vector
speaker_emb_dim: 256
# mel-spectrogram bin size
mel_size: 80
# sampling rate
sampling_rate: 22050

# vector-quantization params
emb_dim: 64
n_embed: 256

# optimizer params
optimizer:
  lr: 0.001

# model params
model:
  dim_neck: 32
  dim_pre: 512
  freq: 32
