# experiment params
exp_name: autovc_vq
seed: 42
batch_size: 512
n_epochs: 200

train_ratio: 0.98

# resemblyzer.VoiceEncoder encodes wav to 256-dim vector
speaker_emb_dim: 256
# mel-spectrogram bin size
mel_size: 80
# sampling rate
sampling_rate: 22050

# optimizer params
optimizer:
  lr: 0.001

# model params
model:
  dim_neck: 32
  dim_pre: 512
  freq: 16

  n_embeddings: 512
  embedding_dim: 32
