# experiment params
exp_name: fragmentvc
seed: 42
batch_size: 512
n_epochs: 2000

train_ratio: 0.98
from_fn: false

# mel-spectrogram bin size
mel_size: 80
# sampling rate
sampling_rate: 22050
# seq_len of spectrum during training
seq_len: 128

# optimizer params
optimizer:
  lr: 0.0005

# model params
model:
  in_channel: 768
  channel: 512
  n_smoother: 3
  n_head: 8
  dropout: 0.1
