# experiment params
exp_name: quartz
seed: 42
batch_size: 256
n_epochs: 1000

train_ratio: 0.9

# resemblyzer.VoiceEncoder encodes wav to 256-dim vector
speaker_emb_dim: 256
# mel-spectrogram bin size
mel_size: 80
# sampling rate
sampling_rate: 22050

# optimizer params
optimizer:
  lr: 0.001

# encoder params
encoder:
  n_block: 5
  n_layers: 5
  c_ins:
    - 512
    - 512
    - 256
    - 256
    - 128
  c_outs:
    - 512
    - 256
    - 256
    - 128
    - 64
  kernels:
    - 9
    - 7
    - 5
    - 3
    - 3
  strides:
    - 1
    - 1
    - 1
    - 1
    - 1
  pads:
    - 4
    - 3
    - 2
    - 1
    - 1

# decoder params
decoder:
  n_block: 5
  n_layers: 5
  c_ins:
    - 64
    - 128
    - 256
    - 256
    - 512
  c_outs:
    - 128
    - 256
    - 256
    - 512
    - 512
  kernels:
    - 9
    - 7
    - 5
    - 3
    - 1
  strides:
    - 1
    - 1
    - 1
    - 1
    - 1
  pads:
    - 4
    - 3
    - 2
    - 1
    - 0
