# experiment params
exp_name: transformer
seed: 42
batch_size: 512
n_epochs: 4000

train_ratio: 0.98
from_fn: false

# mel-spectrogram bin size
mel_size: 80
# sampling rate
sampling_rate: 22050
# seq_len of spectrum during training
seq_len: 128
# whether normalize mel-spectrum
is_normalize: false

# optimizer params
optimizer:
  lr: 0.1

# model params
model:
  in_channel: 80
  channel: 256
  emb_dim: 64
  n_emb: 256
  n_ce: 7
  n_layers: 3
  n_head: 8
  dropout: 0.1
