# experiment params
exp_name: transformer
seed: 42
batch_size: 128
n_epochs: 500

train_ratio: 0.98
from_fn: false

# mel-spectrogram bin size
mel_size: 80
# sampling rate
sampling_rate: 22050
# seq_len of spectrum during training
seq_len: 256
# whether normalize mel-spectrum
is_normalize: false

# optimizer params
optimizer:
  lr: 0.001

# model params
model:
  in_channel: 80
  channel: 256
  emb_dim: 32
  n_emb: 512
  n_ce: 5
  n_layers: 5
  n_smooth: 3
  n_head: 8
  dropout: 0.1
  residual: false
